[package]
name = "calendula"
description = "CLI to manage calendars"
version = "0.2.0"
authors = ["Clément DOUIN (soywod) <clement.douin@posteo.net>"]
edition = "2024"
rust-version = "1.89"
license = "MIT OR Apache-2.0"
categories = ["command-line-utilities"]
keywords = ["cli", "calendar", "caldav", "vdir", "ical"]
homepage = "https://pimalaya.org"
repository = "https://github.com/pimalaya/calendula"

[features]
default = ["rustls-ring", "caldav", "gcal", "msgraph", "vdir", "pimdir", "vendored", "wizard"]
native-tls = ["pimalaya-stream/native-tls", "io-pim-discovery/native-tls", "io-webdav?/native-tls", "io-gcal?/native-tls", "io-msgraph?/native-tls"]
rustls-aws = ["pimalaya-stream/rustls-aws", "io-pim-discovery/rustls-aws", "io-webdav?/rustls-aws", "io-gcal?/rustls-aws", "io-msgraph?/rustls-aws"]
rustls-ring = ["pimalaya-stream/rustls-ring", "io-pim-discovery/rustls-ring", "io-webdav?/rustls-ring", "io-gcal?/rustls-ring", "io-msgraph?/rustls-ring"]
caldav = ["dep:io-webdav", "dep:io-http", "dep:secrecy"]
gcal = ["dep:io-gcal", "dep:secrecy", "io-gcal/ical"]
msgraph = ["dep:io-msgraph", "dep:secrecy", "io-msgraph/client", "io-msgraph/ical"]
vdir = ["dep:io-vdir"]
pimdir = ["dep:io-pimdir"]
vendored = ["pimalaya-stream/vendored", "io-webdav?/vendored", "io-gcal?/vendored", "io-msgraph?/vendored", "io-pimdir?/vendored"]
wizard = ["pimalaya-cli/wizard", "pimalaya-cli/caldav", "pimalaya-cli/spinner"]

[profile.release]
lto = "fat"
codegen-units = 1
strip = "symbols"
panic = "abort"

[build-dependencies]
pimalaya-cli = { version = "0.2", default-features = false, features = ["build"] }

[dev-dependencies]
tempfile = "3"
toml = "1.1"

[dependencies]
anyhow = "1"
chrono = { version = "0.4", default-features = false, features = ["clock", "serde"] }
clap = { version = "4.4", features = ["derive", "env", "wrap_help"] }
crossterm = { version = "0.29", default-features = false, features = ["serde"] }
getrandom = "0.4"
humansize = "2"
ical-rs = { version = "0.5.3", default-features = false, features = ["parser", "tzdb"] }
io-gcal = { version = "0.1.3", default-features = false, features = ["client"], optional = true }
io-msgraph = { version = "0.4.3", default-features = false, optional = true }
io-http = { version = "0.5", default-features = false, optional = true }
io-pim-discovery = { version = "0.8", default-features = false, features = ["autoconfig", "pacc", "rfc6764", "stream"] }
io-pimdir = { version = "0.6", default-features = false, features = ["client"], optional = true }
io-vdir = { version = "0.2", default-features = false, features = ["client", "serde"], optional = true }
io-webdav = { version = "0.5", default-features = false, features = ["client"], optional = true }
jiff = { version = "0.2", default-features = false, features = ["std", "tz-system", "tzdb-bundle-always"] }
log = "0.4"
pimalaya-cli = { version = "0.2", default-features = false, features = ["terminal", "table", "prompt"] }
pimalaya-config = { version = "0.2.1", default-features = false, features = ["toml", "secret"] }
pimalaya-stream = { version = "0.3", default-features = false, features = ["std"] }
schemars = "1"
secrecy = { version = "0.10", optional = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
shellexpand = "3.1"
url = { version = "2.5", features = ["serde"] }
