use std::path::PathBuf;

use anyhow::Result;
use clap::Subcommand;
use pimalaya_cli::printer::Printer;

use crate::{
    account::{check::AccountCheckCommand, list::AccountListCommand},
    backend::Backend,
};

/// Inspect the accounts the configuration declares.
///
/// An account is a named group of backend settings (vdir, pimdir,
/// caldav). Accounts are written by hand or generated by the wizard;
/// these subcommands only read them.
#[derive(Debug, Subcommand)]
pub enum AccountCommand {
    #[command(visible_alias = "ls")]
    List(AccountListCommand),
    Check(AccountCheckCommand),
}

impl AccountCommand {
    pub fn execute(
        self,
        printer: &mut impl Printer,
        config_paths: &[PathBuf],
        account_name: Option<&str>,
        backend: Backend,
    ) -> Result<()> {
        match self {
            Self::List(cmd) => cmd.execute(printer, config_paths),
            Self::Check(cmd) => cmd.execute(printer, config_paths, account_name, backend),
        }
    }
}
